# Permalinks
# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title 
permalink: /:title/

plugins: ["jekyll-sitemap", "jekyll-seo-tag"]

# Setup
title:               "D. Nutter"
tagline:             'Software and Technical Design, Theory, and Musings'
description:         'Software and Technical Design, Theory, and Musings'
#url:                 "http://localhost:4000"
url:                 "https://dsnutter.github.io"
#baseurl:             ''
development: false

# About/contact
author:
  name: "D. Nutter"
  github: dsnutter

# About/contact
author: ds_nutter
authorName: "DS Nutter"
#email: "inquiry@dsnutter.com"
twitter:
  username: "@ds_nutter"
social:
  name: DS Nutter
  links:
    - https://twitter.com/ds_nutter
    - https://github.com/dsnutter
lang: en_US

# Custom vars
version:             1.0.0
# Custom DSN site variables
DSN:
  imagePath: /assets/images
