# Permalinks
# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title 
permalink: /:title/
keep_files: [google42abf95ea02add5b.html]
exclude: [google42abf95ea02add5b.html]

gems: ["jekyll-sitemap"]

# Setup
title:               "D. Nutter"
tagline:             'Software and Technical Design, Theory, and Musings'
description:         ''
#url:                 "http://localhost:4000"
url:                 "http://dsnutter.github.io"
#baseurl:             ''
development: false

# About/contact
author:
  name: "D. Nutter"
  email: ""
  github: dsnutter
  twitter: "@measuredwoodworks"

# Custom vars
version:             1.0.0
# Custom DSN site variables
DSN:
  imagePath: /assets/images
  imagePathPersonal: /assets/images/personal
  analytics: 
    LEC: "UA-55951835-6"

# include custom posts from _personal
collections:
  personal:
    output: true